/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import client.ClientApp;
import javax.swing.JOptionPane;

/**
 *
 * @author dudam
 */
public class Client extends javax.swing.JFrame {

    private ClientApp clientApp;

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inpIP = new javax.swing.JTextField();
        bttnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("IP do servidor");

        inpIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpIPActionPerformed(evt);
            }
        });

        bttnConectar.setText("Conectar");
        bttnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttnConectar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(inpIP)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inpIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(bttnConectar)
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inpIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpIPActionPerformed

    private void bttnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConectarActionPerformed
        String ip = this.inpIP.getText();

        this.clientApp = new ClientApp(ip);
        boolean isConnected = this.clientApp.connect();
        if (isConnected) {
            new Login(clientApp).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(Client.this, "Erro ao conectar ao servidor. Verifique o IP e tente novamente.", "Erro de Conexão", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bttnConectarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnConectar;
    private javax.swing.JTextField inpIP;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
